print ('Bem-vindo á calculadora de hipotenusas!')
n1 = float(input('Digite o cateto oposto: '))
n2 = float(input('Agora o cateto adjacente: '))
hipotenusa = (n2** 2 + n1** 2) ** (1/2)
print('O valor da hipotenusa é de: ', hipotenusa)
