print ('Vamos realizar as 4 operações?')
n1 = int(input('Digite o primeiro número: '))
n2 = int(input('Digite o segundo número: '))
soma = (n1 + n2)
menos = (n1 - n2)
multiplica = (n1 * n2)
divide = (n1 / n2)
print ('Em ordem (Soma, Subtração, Multiplicação e Divisão) o resultado das operações foi: ', {soma}, {menos}, {multiplica}, {divide})
